apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: probes
  name: kube-prometheus-stack-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-prometheus-stack-prometheus
subjects:
  - kind: ServiceAccount
    name: kube-prometheus-stack-prometheus
    namespace: monitoring
