apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: probes
  name: kube-prometheus-stack-prometheus
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
